from faker import Faker
import random

fake = Faker()

def generate_fake_student():
    return {
        "batch": int(random.randint(2020, 2030)),
        "applicationNumber": fake.uuid4(),
        "rank": str(random.randint(1, 5000)),
        "registerNo": fake.bothify(text='??####'),
        "rollNo": fake.bothify(text='ROLL####'),
        "emisNo": fake.bothify(text='EMIS####'),
        "umisNo": fake.bothify(text='UMIS####'),
        "degree": random.choice(["BSc", "BA", "BCom", "BTech"]),
        "course": random.choice(["Computer Science", "Maths", "Physics", "English", "Economics"]),
        "mediumOfStudy": random.choice(["English", "Tamil", "Hindi"]),
        "percentageOfMarks": str(round(random.uniform(50, 100), 2)),
        "name": fake.name(),
        "mobile": fake.msisdn()[0:10],
        "whatsappNo": fake.msisdn()[0:10],
        "email": fake.email(),
        "aadhaarNumber": fake.bothify(text='############'),
        "religion": random.choice(["Hindu", "Muslim", "Christian"]),
        "community": random.choice(["BC", "MBC", "SC", "ST", "OC"]),
        "caste": fake.last_name(),
        "communityCertificateNo": fake.bothify(text='CERT####'),
        "dateOfBirth": str(fake.date_of_birth(minimum_age=17, maximum_age=25)),
        "gender": random.choice(["Male", "Female", "Other"]),
        "bloodGroup": random.choice(["A+", "B+", "AB+", "O+", "O-", "A-", "B-"]),
        "pwd": random.choice(["Yes", "No"]),
        "typesOfDisability": fake.word(),
        "percentageOfDisability": str(random.randint(0, 100)),
        "exServiceMan": random.choice(["Yes", "No"]),
        "ncc": random.choice(["Yes", "No"]),
        "sports": random.choice(["Yes", "No"]),
        "categoryOfSports": fake.word(),
        "admissionQuota": random.choice(["Government", "Management"]),
        "dateOfAdmission": str(fake.date_this_decade()),
        "admissionNumber": fake.bothify(text='ADM####'),
        "presentAddress": fake.address(),
        "communicationAddress": fake.address(),
        "fatherName": fake.name_male(),
        "fatherMobile": fake.msisdn()[0:10],
        "fathersOccupation": fake.job(),
        "fathersEducation": random.choice(["Graduate", "Postgraduate", "Doctorate", "Diploma"]),
        "motherName": fake.name_female(),
        "motherMobile": fake.msisdn()[0:10],
        "mothersOccupation": fake.job(),
        "mothersEducation": random.choice(["Graduate", "Postgraduate", "Doctorate", "Diploma"]),
        "guardianName": fake.name(),
        "guardianNumber": fake.msisdn()[0:10],
        "singleParent": random.choice(["Yes", "No"]),
        "firstGraduate": random.choice(["Yes", "No"]),
        "firstGraduateCertificateNo": fake.bothify(text='FGCERT####'),
        "incomeCertificateNo": fake.bothify(text='INCERT####'),
        "annualIncome": str(random.randint(10000, 500000)),
        "viStandardSchoolName": fake.company(),
        "viStandardCity": fake.city(),
        "viStandardType": random.choice(["Govt", "Private"]),
        "viStandardYearStart": str(random.randint(2005, 2015)),
        "viStandardYearEnd": str(random.randint(2006, 2016)),
        "viiStandardSchoolName": fake.company(),
        "viiStandardCity": fake.city(),
        "viiStandardType": random.choice(["Govt", "Private"]),
        "viiStandardYearStart": str(random.randint(2006, 2016)),
        "viiStandardYearEnd": str(random.randint(2007, 2017)),
        "viiiStandardSchoolName": fake.company(),
        "viiiStandardCity": fake.city(),
        "viiiStandardType": random.choice(["Govt", "Private"]),
        "viiiStandardYearStart": str(random.randint(2007, 2017)),
        "viiiStandardYearEnd": str(random.randint(2008, 2018)),
        "ixStandardSchoolName": fake.company(),
        "ixStandardCity": fake.city(),
        "ixStandardType": random.choice(["Govt", "Private"]),
        "ixStandardYearStart": str(random.randint(2008, 2018)),
        "ixStandardYearEnd": str(random.randint(2009, 2019)),
        "xStandardSchoolName": fake.company(),
        "xStandardCity": fake.city(),
        "xStandardType": random.choice(["Govt", "Private"]),
        "xiStandardYearEnd": str(random.randint(2011, 2021)),
        "xStandardYearStart": str(random.randint(2009, 2019)),
        "xStandardYearEnd": str(random.randint(2010, 2020)),
        "xiStandardSchoolName": fake.company(),
        "xiStandardCity": fake.city(),
        "xiStandardType": random.choice(["Govt", "Private"]),
        "xiStandardYearStart": str(random.randint(2010, 2020)),
        "xiiStandardSchoolName": fake.company(),
        "xiiStandardCity": fake.city(),
        "xiiStandardType": random.choice(["Govt", "Private"]),
        "xiiStandardYearStart": str(random.randint(2011, 2021)),
        "xiiStandardYearEnd": str(random.randint(2012, 2022)),
        "bankName": fake.company(),
        "branch": fake.city(),
        "ifsc": fake.bothify(text='IFSC####'),
        "micr": fake.bothify(text='MICR####'),
        "accountType": random.choice(["Saving", "Current"]),
        "bankAccountNo": fake.bothify(text='##########'),
        "hostlerOrDayScholar": random.choice(["Hostler", "Day Scholar"]),
    }
